# Generated by Django 4.2.4 on 2023-09-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Чат'),
        ),
    ]
