# Generated by Django 4.2.4 on 2023-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='is_pleasant_habit',
            field=models.BooleanField(default=True, verbose_name='Признак приятной привычки'),
        ),
    ]
